ORDER_STATUS_CHOICES = [
    ('DELIVERED', 'DELIVERED'),
    ('ORDER PLACED', 'ORDER PLACED'),
    ('PENDING CONFIRMATION', 'PENDING CONFIRMATION'),
    ('WAITING TO BE SHIPPED', 'WAITING TO BE SHIPPED'),
    ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'),
    ('CANCELLED PAYMENT UNSUCCESSFUL', 'CANCELLED-PAYMENT UNSUCCESSFUL'),
    ('REFUNDED', 'REFUNDED'),
    ('FAILED DELIVERY', 'FAILED DELIVERY'),
]
