# Generated by Django 3.2 on 2023-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
