# Generated by Django 3.2 on 2023-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
