# Generated by Django 3.2 on 2023-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='bank_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
