# Generated by Django 3.2 on 2024-01-01 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_useraccount_recipient_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
