# Generated by Django 3.2 on 2023-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20231106_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
