# Generated by Django 3.2 on 2024-01-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivate_account',
            field=models.BooleanField(default=False),
        ),
    ]
