# Generated by Django 3.2 on 2024-01-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240101_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deactivate_account',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
