# Generated by Django 3.2 on 2024-03-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('withdrawal_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('source_details', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('failures', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('titan_code', models.CharField(blank=True, max_length=255, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.IntegerField(blank=True, null=True)),
                ('request', models.IntegerField(blank=True, null=True)),
                ('recipient', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
