# Generated by Django 3.2 on 2024-03-18 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(db_index=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('ORDER PLACED', 'ORDER PLACED'), ('PENDING CONFIRMATION', 'PENDING CONFIRMATION'), ('WAITING TO BE SHIPPED', 'WAITING TO BE SHIPPED'), ('OUT FOR DELIVERY', 'OUT FOR DELIVERY'), ('CANCELLED PAYMENT UNSUCCESSFUL', 'CANCELLED-PAYMENT UNSUCCESSFUL'), ('REFUNDED', 'REFUNDED'), ('FAILED DELIVERY', 'FAILED DELIVERY')], default='PENDING_CONFIRMATION', max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_tag', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('varient', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(db_index=True)),
                ('price', models.FloatField(db_index=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.shippingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
