# Generated by Django 3.2 on 2023-11-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
