# Generated by Django 3.2 on 2023-10-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
